### ISSUE TITLE
No Star Trek Data for the First Tutorial

### ISSUE THREAD

**Issue by educatorsRlearners** [jina-ai/examples#170]
As the subject line states, while following the [Build Your First Neural Search App tutorial](https://github.com/jina-ai/examples/tree/master/my-first-jina-app#build-your-first-neural-search-app), I found that I couldn't download the Star Trek [data](https://github.com/jina-ai/examples/tree/master/my-first-jina-app#download-data). 

In fact, it downloaded the _South Park_ data instead. 

![no_data_edited](https://user-images.githubusercontent.com/17770276/91190242-ac470b80-e6f3-11ea-8cad-831ee4cf0cf4.png)

**Comment by theUnkownName** [comment]
Hi @educatorsRlearners 
Thanks for letting us know, do you have the latest version? I just tried and I got the star trek data.

I used the cookicutter `pip install -U cookiecutter && cookiecutter gh:jina-ai/cookiecutter-jina`, got the docker image `docker run -p 45678:45678 jinaai/hub.app.distilbert-southpark` (I see that it says south park, but it shouldn't matter) installed requierements `pip install -r requirements.txt` downloaded the dataset
 `cd ..`
`bash ./get_data.sh` and got the star trek data. Is there something I did different from you?

**Comment by educatorsRlearners** [comment]
Hello @theUnkownName 

jina = 0.4.11
Python 3.7.7

As for if you did something different, I'm really not sure. 

What I do know is I followed the tutorial step-by-step.

``git clone git@github.com:alexcg1/my-first-jina-app.git ``
``cd my-first-jina-app``
``pip install -U cookiecutter && cookiecutter gh:jina-ai/cookiecutter-jina``
``cd star_trek``
`` pip install -r requirements.txt``
`` cd ..``
``bash ./get_data.sh``
``cd star_trek``

and when I ran this line: 
``head data/startrek_tng.csv

I got: 

``head: cannot open 'data/startrek_tng.csv' for reading: No such file or directory``

Like most things, I'm sure it's something small that I'm doing wrong but I just don't know what it is. 

Cheers!

**Comment by davidecadamuro** [comment]
I found the missing data in the github repo of the author: https://github.com/alexcg1/ml-datasets

I solved the issue with 

```
mkdir data
cd data
wget https://raw.githubusercontent.com/alexcg1/ml-datasets/master/nlp/startrek/startrek_tng.csv
```

I hope this helps.

**Comment by alexcg1** [comment]
Huh, that's weird. It worked okay the last time I tested it! I would fix the bug but...the tutorial is being retired since cookiecutter-jina is no longer supported. More info on that below:

---

 Unfortunately cookiecutter-jina no longer works with Jina's latest code, so we've made the difficult decision to retire this tutorial until we have a more effective way for new users to bootstrap a simple Jina project.

When I wrote the tutorial (when Jina 0.3.0 was the latest release) it worked perfectly. Alas with the breaking changes of 0.4.0 that's no longer the case.

Please let me know if you have any other questions or feedback!
