### ISSUE TITLE
Random results with multilingual search tutorial

### ISSUE THREAD

**Issue by denysthegitmenace** [jina-ai/examples#182]
I am trying to make the multilingual search example work, but the query gives super random results. I indexed only one of the files - namely one for en 2011. I compiled a sample of the random results the query returns here ->> https://docs.google.com/spreadsheets/d/1gdylpmYQZAimuDjFTKQznF2mal7uOkd4J-9BDQVwOSo/edit?usp=sharing Could someone check this out and hopefully advice on what could be done to improve the accuracy?

**Comment by deepankarm** [comment]
Hey @denysthegitmenace, 

Glad to know that you're interested in exploring Jina.

The multilingual search example is based on [Laser Embeddings](https://github.com/facebookresearch/LASER). In the example code, we are using a [simple (small) news dataset](https://github.com/jina-ai/examples/blob/master/multilingual-search/get_data.sh#L11) for indexing & querying. If we index the datasets in [multiple languages](https://github.com/jina-ai/examples/blob/master/multilingual-search/app.py#L15) (say English, German & French) and search for an already existing news headline text during a query, we'll find the relevant texts in all indexed languages. Since the dataset is very small & not generic, we would get random results if we just index for one language.

Laser team also provides a different [multilingual dataset](https://github.com/facebookresearch/LASER/tree/master/data/tatoeba/v1) supporting 112 languages. Feel free to extend the example on this dataset. You can also explore other datasets to get better results.

**Comment by denysthegitmenace** [comment]
Thank you so much for looking into this, Deepankar! I am struggling to understand how indexing one language only sacrificed the search accuracy. Is there any chance you could explain me why that is the case?
