### ISSUE TITLE
pokedex: unknown exception: [Errno 13] Permission denied: 'workspace/chunk_compound_indexer-1'

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#214]
Trying to run:

```sh
docker run -v "$(pwd)/data:/data" -v "$(pwd)/workspace:/workspace" -e "JINA_LOG_PROFILING=1" -p 5000:5000 jinaai/hub.app.bitsearch index
```
Throws a whole bunch of errors like:

```sh
unknown exception: [Errno 13] Permission denied: 'workspace/chunk_compound_indexer-1'
```

**Context**

* I ran `download.sh` to download the model
* All reqs installed in venv
* Manually created `workspace` folder (it wasn't there before)
* Created `data` folder and put Pokemon data inside (see [data.txt](https://github.com/jina-ai/examples/files/5239557/data.txt))
* Pokemon data from the `tar.gz` files @hanxiao shared on Slack

Log file from Docker: [log.txt](https://github.com/jina-ai/examples/files/5239564/log.txt)

**Comment by JamesTang-jinaai** [comment]
probably because you installed docker with sudo or with root. After running docker, it create some file in your workspace, like `workspace/chunk_compound_indexer-1`, do solve this problem, you need to add your current user to docker group. Here are the steps you may want to follow:
1.check where you have docker group
```bash
groups
```
should be like this:
```
jamestang adm cdrom sudo dip plugdev lpadmin lxd sambashare docker
```

2. add user XXX to docker
```bash
usermod -a -G docker XXX
```
3. check 
```bash
grep docker /etc/group
```
it should be like this:
```bash
docker:x:998:jamestang
```
4. restart docker
```bash
service docker restart
```
5.restart or login again
6. check if docker works without sudo
```bash
docker images
```
7. delete your workspace and run your python app again.
