### ISSUE TITLE
TransformerTorchEncoder Post Request

### ISSUE THREAD

**Issue by agemagician** [jina-ai/examples#303]
Hello,

After running:
`sudo docker run --rm -p 55555:55555 -p 55556:55556 jinaai/hub.executors.encoders.nlp.transformers-pytorch --port-in 55555 --port-out 55556`

Could you please write an example for a post request for the "TransformerTorchEncoder" ?

Furthermore, how I can figure it out ? because there is no examples or documentation for using it.

I have also check this example:
https://github.com/jina-ai/examples/tree/master/x-as-service
But it doesn't run and gives the following error:
```
/home/agemagician/anaconda3/envs/jina/lib/python3.8/site-packages/jina/importer.py:134: UserWarning: due to the missing dependencies or bad implementations, ['jina.hub.encoders.nlp.VSETextEncoder', 'jina.hub.encoders.image.VSEImageEncoder'] can not be imported if you are using these executors/drivers, they wont work. You can use `jina check` to list all executors and drivers
  warnings.warn(
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from jina.drivers.helper import pb2array
ModuleNotFoundError: No module named 'jina.drivers.helper'
```

**Comment by JoanFM** [comment]
Hello @agemagician,

Thank you very much for your interest in jina.

For the first question:
- I think there is a missunderstanding on how a `Hub Executor` works, it cannot receive POST requests when used alone, the POST requests in jina are sent to the `GATEWAY` which is created with a `Flow` object. (https://github.com/jina-ai/jina#get-started) Otherwise, this Pod that u are starting with this `docker` command is not reachable from a REST or any GRPC client.

- As you can see in the examples the easiest way to connect Pods between them and passing messages through them is by using a Flow.

You could have a Flow which would look similar to this:

```python
from jina.flow import Flow

with Flow(rest_api: True, port_expose=45678).add(uses='jinaai/hub....') 
```

Then you can start sending Requests to the gateway at port 45678

As per the second question:
- Please be aware that this example is old and has not been updated for the newest jina versions. What jina version are you trying to use?

Thank you very much

**Comment by theUnkownName** [comment]
Hi @agemagician 

I didn't catch the first part of your question, but regarding on examples with the `TransformerTorchEncoder` we use it in several ones, I think the easiest would be to check `my-first-jina-app` and the `encode.yml` file uses this Transfomer, so maybe this could be helpful to you. Let me know if this works.

**Comment by agemagician** [comment]
Thanks a lot for your explanation.

It is now more clearer to me.

I just installed Jina from your repo, so I assume it is the latest jina version.

Could you please share an updated version of x-as-service for embedding, with a clear step by step example for the whole pipeline "running the Hub Executor, getaway, sending post, receiving the results" from sending the post request using postman for example until I receive the embedding ?

Thanks again for your time and effort.

**Comment by JoanFM** [comment]
> Thanks a lot for your explanation.
> 
> It is now more clearer to me.
> 
> I just installed Jina from your repo, so I assume it is the latest jina version.
> 
> Could you please share an updated version of x-as-service for embedding, with a clear step by step example for the whole pipeline "running the Hub Executor, getaway, sending post, receiving the results" from sending the post request using postman for example until I receive the embedding ?
> 
> Thanks again for your time and effort.

Hello @agemagician.

We do not have the capacity right now to mantain all the examples with the latest jina versions.

But what you ask can be extracted from different examples that use different hub encoders to extract embeddings and which are queries using Rest curl commands.

Thanks
