### ISSUE TITLE
Any example for video search?

### ISSUE THREAD

**Issue by LegendaryDan** [jina-ai/examples#666]
If there is an example or demo for video search plus a simple front end, that would be super cool! :)

Thanks.

**Comment by Yongxuanzhang** [comment]
Hi, we have a gif search example in Jina 1.0. with a simple forntend 
https://github.com/jina-ai/examples/tree/master/tumblr-gif-search
But in 2.0 we don't keep it

**Comment by alexcg1** [comment]
Hey @LegendaryDan , good to have you here!

I've created a [meme image search example](https://github.com/alexcg1/jina-meme-search-image-backend) (still a WIP) using Jina 2.0. You should be able to write a new generator that takes in `*.mp4`, `*.webm`, etc and instead of the image encoder executor you could swap in a video encoder.

There's also a [front-end](https://github.com/alexcg1/jina-meme-search-frontend) written in Streamlit.

Would love to see what you come up with!

**Comment by jakob1111996** [comment]
@alexcg1 Will we create a video example or should we close this issue?

**Comment by alexcg1** [comment]
Now that Hub  is on the way,  I'm  planning to  create a simple video search example. Just  need to  wait  for things  to  stabilize a little bit more. But we can close this for now.
