### ISSUE TITLE
Lyrics Search indexing is very slow

### ISSUE THREAD

**Issue by canetcesc** [jina-ai/examples#97]
On the Lyrics search example, I run indexing via Docker but it takes a long time (it has been running for 3 hours). It is unclear to me what exactly is indexing (the toy data or the full data) because when running search for the first time it initially downloads a 263MB file which I suspect is the full dataset.

Just wanted to know from your end:

1. How long does it take (approximately) to you to run the index on a laptop machine (both for the toy dataset and the full dataset)?

2. How can I know during indexing if it is indexing the full dataset or the toy dataset?

3. Can indexing time be improved significantly by using a GPU machine?

4. While indexing, files are generated in the `./workspace` folder.  However, errors are returned if I try to perform a search before indexing ends. Particularly:
`you can not query from NumpyIndexer as its "query_handler" is not set. If you are indexing data from scratch then it is fine. If you are querying data then the index file must be empty or broken`  and  `'NoneType' object has no attribute 'shape'`. Is it so that indexing has to complete before search can be performed upon, meaning it is not possible to run searches on a partial index?

5. Is indexing necessary when running it via Docker, or does the Docker image already contain indices?

**Comment by JoanFM** [comment]
Hello @canetcesc ,
Thank you for trying Jina out. It is definitely an expensive example to play around with your desktop.

Let me try to clarify yout questions:

1. It is unclear and very dependant on the hardware capabilities, but it is indeed very expensive for a desktop, since Bert model is very heavy.

2. If you check the contents of `app.py` you will see that it is the full dataset being indexed. Maybe you can try to index toy dataset in order to be able to play with it.

3. It should definitely improve to run the encoder in the GPU.

4. For now, it is not possible to run queries while indexing. It is something that we definitely want to cover in the future.

5. The docker image does not contain any indexing, so it is necessary to index.

I hope you find these insights helpful

**Comment by canetcesc** [comment]
Thanks / Merci 👍
