### ISSUE TITLE
adapt faiss to the latest indexer api

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/examples#98]
the yaml files might needs to change.

[https://github.com/jina-ai/examples/blob/master/faiss-search/yaml/index-chunk.yml#L5](https://github.com/jina-ai/examples/blob/master/faiss-search/yaml/index-chunk.yml#L5)

Reference:

[https://github.com/jina-ai/jina/pull/592](https://github.com/jina-ai/jina/pull/592)

**Comment by JoanFM** [comment]
Regarding jina-ai/jina#592, isn't it already the case in faiss-search that it is using the index files created at indexing time? or is it just because **FaissIndexer** is used also as index time?

For now, best practice would be to use a plain **NumpyIndexer** at index time, and a **FaissIndexer** or **AnnoyIndexer** with the latter **NumpyIndexer** as ref_indexer at query time?
